### ISSUE TITLE
The poor Instance Segmentation performance on COCO

### ISSUE THREAD

**Issue by gzbird** [bowenc0221/panoptic-deeplab#65]
Hi, I am curious why the Instance segmentation performance on Cityscapes seems acceptable, but that on COCO is so poor? 

What do you think may be the reason for this?  Thank you in advance.

**Comment by bowenc0221** [comment]
Few thoughts:
1. COCO has larger range of objects, so FPN is important. Current Panoptic-DeepLab only uses a single scale feature for detection. I would assume using FPN can improve performance a lot on COCO.
2. AP metric itself is in favor of high recall. This is especially the case for COCO dataset. That's why top-down methods like Mask R-CNN shine on COCO.

**Comment by gzbird** [comment]
Thank you so much !

**Comment by ghost** [comment]
> Few thoughts:
> 
> 1. COCO has larger range of objects, so FPN is important. Current Panoptic-DeepLab only uses a single scale feature for detection. I would assume using FPN can improve performance a lot on COCO.
> 2. AP metric itself is in favor of high recall. This is especially the case for COCO dataset. That's why top-down methods like Mask R-CNN shine on COCO.
> 3. I did not find the optimal training parameters on COCO.

Thank you so much!
