### ISSUE TITLE
Config file for COCO (old version)

### ISSUE THREAD

**Issue by aoussou** [bowenc0221/panoptic-deeplab#79]
Hello,

I know it is deprecated, but I'd like to try to train the old version of the code on the COCO dataset. Would you happen to have the relevant config file by any chance? (I think you only have cityscapes config files).

**Comment by bowenc0221** [comment]
Unfortunately, I do not have COCO config for the older version because I didn't try much on COCO with my old code. Most experiments on COCO were conducted after I reproduce Panoptic-DeepLab on Detectron2.

You can refer to my log posted in this issue https://github.com/bowenc0221/panoptic-deeplab/issues/4#issuecomment-720242563. But that config cannot reproduce the 35.5 PQ result.
